import { Footer, Header } from '@/shared/ui';
import Head from 'next/head';
import React, { FC, PropsWithChildren } from 'react';
import { Providers } from '@/app/providers';

const Layout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <React.Fragment>
      <Head>
        <title>Toxin</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
        <link
          rel='preconnect'
          href='https://fonts.googleapis.com'
        />
        <link
          rel='preconnect'
          href='https://fonts.gstatic.com'
        />
        <link
          href='https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap'
          rel='stylesheet'
        ></link>
      </Head>
      <Providers>
        <Header />
        <main className='page'>{children}</main>
        <Footer />
      </Providers>
    </React.Fragment>
  );
};

export default Layout;
