import { Room } from "@/entities/room";

export const ELEMENT_PER_SLIDE = 12;
export const ROOMS: Room[] = [
    {
        id: 1,
        type: 'LUXE',
        number: 888,
        created: new Date(),
        day_price: 9900,
        is_deleted: false,
        services_price: 300,
        additional_services_price: 0,
        updated: new Date(),
    },
    {
        id: 2,
        type: 'DEFAULT',
        number: 840,
        created: new Date(),
        day_price: 9900,
        is_deleted: false,
        services_price: 300,
        additional_services_price: 0,
        updated: new Date(),
    },
    {
        id: 3,
        type: 'DEFAULT',
        number: 841,
        created: new Date(),
        day_price: 9900,
        is_deleted: false,
        services_price: 300,
        additional_services_price: 0,
        updated: new Date(),
    },
    {
        id: 4,
        type: 'DEFAULT',
        number: 842,
        created: new Date(),
        day_price: 9200,
        is_deleted: false,
        services_price: 300,
        additional_services_price: 0,
        updated: new Date(),
    },
    {
        id: 5,
        type: 'DEFAULT',
        number: 843,
        created: new Date(),
        day_price: 8100,
        is_deleted: false,
        services_price: 300,
        additional_services_price: 0,
        updated: new Date(),
    },
    {
        id: 6,
        type: 'DEFAULT',
        number: 843,
        created: new Date(),
        day_price: 8100,
        is_deleted: false,
        services_price: 300,
        additional_services_price: 0,
        updated: new Date(),
    },
    {
        id: 7,
        type: 'DEFAULT',
        number: 843,
        created: new Date(),
        day_price: 8100,
        is_deleted: false,
        services_price: 300,
        additional_services_price: 0,
        updated: new Date(),
    },
    {
        id: 8,
        type: 'DEFAULT',
        number: 843,
        created: new Date(),
        day_price: 8100,
        is_deleted: false,
        services_price: 300,
        additional_services_price: 0,
        updated: new Date(),
    },
    {
        id: 9,
        type: 'DEFAULT',
        number: 843,
        created: new Date(),
        day_price: 8100,
        is_deleted: false,
        services_price: 300,
        additional_services_price: 0,
        updated: new Date(),
    },
    {
        id: 10,
        type: 'DEFAULT',
        number: 843,
        created: new Date(),
        day_price: 8100,
        is_deleted: false,
        services_price: 300,
        additional_services_price: 0,
        updated: new Date(),
    },
    {
        id: 11,
        type: 'DEFAULT',
        number: 843,
        created: new Date(),
        day_price: 8100,
        is_deleted: false,
        services_price: 300,
        additional_services_price: 0,
        updated: new Date(),
    },
    {
        id: 12,
        type: 'DEFAULT',
        number: 843,
        created: new Date(),
        day_price: 8100,
        is_deleted: false,
        services_price: 300,
        additional_services_price: 0,
        updated: new Date(),
    },
    {
        id: 13,
        type: 'DEFAULT',
        number: 843,
        created: new Date(),
        day_price: 8100,
        is_deleted: false,
        services_price: 300,
        additional_services_price: 0,
        updated: new Date(),
    },
];
export const TOTAL_PAGE = Math.ceil(ROOMS.length / ELEMENT_PER_SLIDE);