// eslint-disable-next-line no-restricted-imports
import '@/app/styles/index.scss'
import type { AppProps } from 'next/app'
import Head from 'next/head'

// eslint-disable-next-line no-restricted-imports
import { Providers } from '@/app/providers'

import { Layout } from '@/widgets/layouts'

export default function App({
	Component,
	pageProps: { session, ...pageProps },
}: AppProps) {
	return (
		<Providers session={session}>
			<Layout>
				<Head>
					<title>Toxin</title>
					<meta name='description' content='Generated by create next app' />
					<meta name='viewport' content='width=device-width, initial-scale=1' />
				</Head>
				<Component {...pageProps} />
			</Layout>
		</Providers>
	)
}
