import '@/app/styles/index.scss';
import type { AppProps } from 'next/app';
import { Providers } from '@/app/providers';
import { Layout } from '@/widgets/layouts/base';
import Head from 'next/head';

export default function App({
  Component,
  pageProps: { session, ...pageProps },
}: AppProps) {
  return (
    <Providers session={session}>
      <Layout>
        <Head>
          <title>Toxin</title>
          <meta
            name='description'
            content='Generated by create next app'
          />
          <meta
            name='viewport'
            content='width=device-width, initial-scale=1'
          />
        </Head>
        <Component {...pageProps} />
      </Layout>
    </Providers>
  );
}
